version: "3.8"

services:
  postgres:
    image: postgres:16.3-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - PGPORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -p ${POSTGRES_PORT} -d ${POSTGRES_DB_NAME}
      interval: 1s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000" # The API port for MinIO
      - "9001:9001" # Port for MinIO Console (Web interface)
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

  # Working only for tests and local development
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    environment:
      - MH_STORAGE=maildir
      - MH_HTTP_BIND_ADDR=0.0.0.0:8025
      - MH_SMTP_BIND_ADDR=0.0.0.0:1025
    ports:
      - "1025:1025" # SMTP port for sending mail
      - "8025:8025" # Web interface for viewing emails
    volumes:
      - mailhog_data:/MailHog/data

volumes:
  pgdata:
  pgadmin_data:
  minio_data:
  mailhog_data:
