// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.example.com/support"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/capsules": {
            "post": {
                "description": "Creates a new time capsule with the given parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capsules"
                ],
                "summary": "Create a new capsule",
                "parameters": [
                    {
                        "description": "Capsule creation payload",
                        "name": "capsule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateCapsuleRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Capsule created successfully",
                        "schema": {
                            "$ref": "#/definitions/models.CapsuleResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to create capsule",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/feedback": {
            "post": {
                "description": "Stores user feedback in the database",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "feedback"
                ],
                "summary": "Submit user feedback",
                "parameters": [
                    {
                        "description": "Feedback data",
                        "name": "feedback",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateFeedbackRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Feedback successfully created",
                        "schema": {
                            "$ref": "#/definitions/models.FeedbackResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid input data",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/generate-presigned-url": {
            "get": {
                "description": "Generates a presigned URL for uploading a file to a specific directory (UUID) in MinIO.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "file"
                ],
                "summary": "Generate a presigned URL for file upload",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Target directory UUID",
                        "name": "directory",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Presigned URL generated successfully",
                        "schema": {
                            "$ref": "#/definitions/models.PresignedURLResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to generate presigned URL",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/send-test-email": {
            "post": {
                "description": "Generates and sends a test email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "email"
                ],
                "summary": "Send a test email",
                "parameters": [
                    {
                        "description": "Email payload",
                        "name": "email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.EmailDataRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Email sent successfully"
                    },
                    "400": {
                        "description": "Invalid input data",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Failed to send email",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CapsuleResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Date and time when the capsule was created",
                    "type": "string"
                },
                "files_folder_uuid": {
                    "description": "Optional folder UUID for files",
                    "type": "string"
                },
                "id": {
                    "description": "Capsule ID",
                    "type": "integer"
                },
                "message": {
                    "description": "Message text",
                    "type": "string"
                },
                "recipient_email": {
                    "description": "Recipient's email address",
                    "type": "string"
                },
                "send_at": {
                    "description": "Date and time when the capsule is scheduled to be sent",
                    "type": "string"
                },
                "sender_name": {
                    "description": "Sender's name",
                    "type": "string"
                },
                "status": {
                    "description": "Status of the capsule (e.g., pending, sent)",
                    "type": "string"
                }
            }
        },
        "models.CreateCapsuleRequest": {
            "type": "object",
            "required": [
                "message",
                "recipient_email",
                "send_at",
                "sender_name"
            ],
            "properties": {
                "files_folder_uuid": {
                    "description": "Optional folder UUID for files",
                    "type": "string",
                    "example": "07023417-5079-429d-a113-cbef2ef164d7"
                },
                "message": {
                    "description": "Message text to be sent",
                    "type": "string",
                    "maxLength": 4096,
                    "example": "Test Message"
                },
                "recipient_email": {
                    "description": "Recipient's email address",
                    "type": "string",
                    "example": "test@example.com"
                },
                "send_at": {
                    "description": "Send date in string format",
                    "type": "string",
                    "example": "2024-11-18"
                },
                "sender_name": {
                    "description": "Sender's name",
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "models.CreateFeedbackRequest": {
            "type": "object",
            "required": [
                "message"
            ],
            "properties": {
                "message": {
                    "description": "The feedback message (up to 4096 characters)",
                    "type": "string",
                    "maxLength": 4096,
                    "example": "Test Message"
                }
            }
        },
        "models.EmailDataRequest": {
            "type": "object",
            "required": [
                "body",
                "recipient_email",
                "subject"
            ],
            "properties": {
                "body": {
                    "description": "Body content of the email with a maximum character limit",
                    "type": "string",
                    "maxLength": 4096,
                    "example": "Test body"
                },
                "files_folder_uuid": {
                    "description": "Optional UUID for the folder containing attachments",
                    "type": "string",
                    "example": "07023417-5079-429d-a113-cbef2ef164d7"
                },
                "recipient_email": {
                    "description": "Recipient's email address",
                    "type": "string",
                    "example": "test@example.com"
                },
                "subject": {
                    "description": "Subject of the email",
                    "type": "string",
                    "example": "Test subject"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "description": "A brief description of the error",
                    "type": "string"
                }
            }
        },
        "models.FeedbackResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "The date and time when the feedback was created",
                    "type": "string"
                },
                "id": {
                    "description": "The unique identifier for the feedback",
                    "type": "integer"
                },
                "message": {
                    "description": "The feedback message content",
                    "type": "string"
                }
            }
        },
        "models.PresignedURLResponse": {
            "type": "object",
            "properties": {
                "presigned_url": {
                    "description": "The generated presigned URL for file upload",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "backend.localhost",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Time Capsule Memories API",
	Description:      "REST API backend for the Time Capsule Memories project.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
