// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "http://www.example.com/support"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/capsules": {
            "post": {
                "description": "Создает новое событие с заданными параметрами",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capsules"
                ],
                "summary": "Создать новое событие",
                "parameters": [
                    {
                        "description": "Данные для создания события",
                        "name": "capsule",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateCapsule"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Успешно создано событие",
                        "schema": {
                            "$ref": "#/definitions/models.CapsuleResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректные данные",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Не удалось создать событие",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CapsuleResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "files_folder_uuid": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "recipient_email": {
                    "type": "string"
                },
                "recipient_tg_username": {
                    "type": "string"
                },
                "send_at": {
                    "type": "string"
                },
                "sender_name": {
                    "type": "string"
                }
            }
        },
        "models.CreateCapsule": {
            "type": "object",
            "required": [
                "message",
                "recipient_email",
                "recipient_tg_username",
                "send_at",
                "sender_name"
            ],
            "properties": {
                "files_folder_uuid": {
                    "type": "string",
                    "example": "07023417-5079-429d-a113-cbef2ef164d7"
                },
                "message": {
                    "type": "string",
                    "example": "Test Message"
                },
                "recipient_email": {
                    "type": "string",
                    "example": "test@example.com"
                },
                "recipient_tg_username": {
                    "type": "string",
                    "example": "testuser"
                },
                "send_at": {
                    "type": "string",
                    "example": "2024-11-18"
                },
                "sender_name": {
                    "type": "string",
                    "example": "John Doe"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Time Capsule Memories API",
	Description:      "This is a sample server for Time Capsule Memories.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
